[all]
10.10.10.104 ansible_become_password='ambient'
10.10.10.105 ansible_become_password='ambient'
10.10.10.106 ansible_become_password='ambient'

[apache]
10.10.10.106 ansible_become_password='ambient'
