---
- name: tp0 install vim + check /etc/password
  hosts: all
  remote_user: ambient-user
  become: true
  become_user: root
  vars:
    salut: /tmp/salut
    passwordFile: /etc/passwd
    salutmonpote: /tmp/salutmonpote
  tasks:

  - name: Install vim
    ansible.builtin.apt:
      name: vim
      state: present

  - name: check {{ passwordFile }}
    ansible.builtin.file:
      path: "{{ passwordFile }}"
      state: file

  - name: absent {{ salut }}
    ansible.builtin.file:
      path: "{{ salut }}" 
      state: absent

  - name: creation {{ salutmonpote }}
    ansible.builtin.file:
      path: "{{ salutmonpote }}" 
      state: absent

  - name: write {{ salutmonpote }}
    ansible.builtin.lineinfile:
        path: "{{ salutmonpote }}"
        line: "{{ ansible_hostname }}  {{ ansible_date_time.date }}"
        mode: '0644'
        create: true

  - name: check {{ salutmonpote }}
    ansible.builtin.file:
      path: "{{ salutmonpote }}"
      state: file

